### ISSUE TITLE
CRITICAL: Bitfields and heads must be included every block

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#2937]
## Describe the bug

- Running gossamer using the chain configuration `westend-local` I face the following **critical** log message
```
CRITICAL target=runtime message=panicked at 'Bitfields and heads must be included every block', /builds/runtime/parachains/src/paras_inherent/mod.rs:200:17	imports.go:L140:ext_logging_log_version_1

WARN     failed to handle slot 278029812: cannot finalise block: running runtime function: Failed to call the `BlockBuilder_finalize_block` exported function.
```
- This error happens in the right after I start the nodes, here is the full log: https://gist.github.com/EclesioMeloJunior/4eff5eb0a2c88ad6313fdd19c100b370

## Additional Informations

- I am using the latest changes in development branch
- the config file I am using is:
```toml
[global]
basepath = "./tmp/westend"
log = "info"
metrics-address = ":9876"

[log]
core = ""
network = "trace"
rpc = ""
state = ""
runtime = ""
babe = ""
grandpa = ""
sync = "trace"
digest = ""

[init]
genesis = "./chain/westend-local/westend-local-spec-raw.json"

[account]
key = "bob"
unlock = ""

[core]
roles = 4
babe-authority = true
grandpa-authority = true
babe-lead = true

[network]
port = 7001
nobootstrap = false
nomdns = false

[rpc]
enabled = true
ws = true
port = 8545
host = "localhost"
modules = [
    "system",
    "author",
    "chain",
    "state",
    "rpc",
    "grandpa",
    "offchain",
    "childstate",
    "syncstate",
    "payment",
]
ws-port = 8546

[pprof]
listening-address = "localhost:6060"
block-rate = 0
mutex-rate = 0

```
