### ISSUE TITLE
Cannot handle home dir

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/gossamer#496]
## Expected Behavior

Should expand `~` to home dir.

## Current Behavior

Creates directory `./~` when starting gossamer

## Steps to Reproduce (for bugs)

1. `./build/bin/gossamer init --genesis genesis.json`
2. `gossamer --config ./config.toml `
3. `ls -la `

config.toml:
```toml
[global]
data-dir = "~/.gossamer"
```
