### ISSUE TITLE
Add codeclimate config

### ISSUE THREAD

**Issue by thomasmodeneis** [ChainSafe/gossamer#860]
## Expected Behavior

- As a developer, I would like to have my PRs merged without this intervention when code climate rules are not matching common rules.

## Current Behavior

- Currently, codeclimate is a bit in the way with some opinions that differ a bit from standard lint, making it our lifes as dev more difficult at times. For example with Cognitive Complexity, and Similar blocks of code found.

Example: https://codeclimate.com/github/ChainSafe/gossamer/pull/843

What happens is if there is such issue, the PR can only be merged by the admin, making the process slower and more cumbersome.

## Possible Solution

Add `.codeclimate.yml` file with following content:

```
version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
plugins:
  gofmt:
    # Codeclimate go fmt does not agree with tip go fmt; consider re-enabling
    # CC when the advice matches up with tip again.
    enabled: false
  govet:
    enabled: true
  golint:
    enabled: true
exclude_paths:
  - testdata
```
Example source: https://raw.githubusercontent.com/golang/dep/master/.codeclimate.yml

-

## Steps to Reproduce

1.
2.
3.
4.

## Specification

- go version:
- gossamer version:
- gossamer commit tag:
- gossamer commit hash:
- operating system:
- additional links:

## Checklist

- [ ] I have read [CONTRIBUTING](CONTRIBUTING.md) and [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
- [ ] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself
